C# Web/ASP.NET Advanced/Web Application Security and ASP.NET Core - Lab/PT-HospitalApp/Models/ErrorViewModel.cs
using System;

namespace PT_HospitalApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

C# Web/ASP.NET Advanced/Web Application Security and ASP.NET Core - Lab/PT-HospitalApp/Models/ExaminationRecord.cs
using System;

namespace PT_HospitalApp.Models
{
    public class ExaminationRecord
    {
        public string PatientEmail { get; set; }
        public string Diagnosis { get; set; }
        public DateTime Date { get; set; }
        public string DoctorName { get; set; }
        public string DoctorSpeciality { get; set; }
    }
}

C# Web/ASP.NET Advanced/Web Application Security and ASP.NET Core - Lab/PT-HospitalApp/Models/MedicalRecord.cs
using System;

namespace PT_HospitalApp.Models
{
    public class MedicalRecord
    {
        // Solution: use Guid instead of int
        public Guid Id { get; set; }
        public DateTime Date { get; set; }
        public string DoctorName { get; set; }
    }
}

C# Web/ASP.NET Advanced/Web Application Security and ASP.NET Core - Lab/PT-HospitalApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PT_HospitalApp.Models;
using System.Diagnostics;

namespace PT_HospitalApp.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

C# Web/ASP.NET Advanced/Web Application Security and ASP.NET Core - Lab/PT-HospitalApp/Controllers/MedicalHistoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PT_HospitalApp.Data;
using PT_HospitalApp.Models;
using System.Linq;
using System.Security.Claims;

namespace PT_HospitalApp.Controllers
{
    [Authorize]
    public class MedicalHistoryController : Controller
    {
        private HospitalDbContext data;
        public MedicalHistoryController(HospitalDbContext data)
            => this.data = data;

        public IActionResult Summary()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var records = this.data.Examinations
                .Where(ex => ex.PatientId == userId)
                .Select(ex => new MedicalRecord()
                {
                    Id = ex.Id,
                    Date = ex.Date,
                    DoctorName = ex.DoctorName
                })
                .ToList();

            return View(records);
        }

        public IActionResult Details(int examinationId)
        {
            var examination = this.data
                .Examinations
                .Include(ex => ex.Patient)
                .FirstOrDefault(ex => ex.Id == examinationId);
                
            if (examination == null)
            {
                return RedirectToAction("Summary");
            }

            var model = new ExaminationRecord()
            {
                Date = examination.Date,
                Diagnosis = examination.Diagnosis,
                DoctorName = examination.DoctorName,
                DoctorSpeciality = examination.DoctorSpeciality,
                PatientEmail = examination.Patient.Email
            };

            return View(model);
        }
    }
}

C# Web/ASP.NET Advanced/Web Application Security and ASP.NET Core - Lab/PT-HospitalApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HospitalApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HospitalApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="MedicalHistory" asp-action="Summary">Medical Records</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HospitalApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>